mode = "dark"
accent = "#ff87d1"
selection = "#472749"
muted = "#a695a9"
background = "#24152f"
dark_background = "#130c1c"
darker_background = "#0f0a16"
lighter_background = "#31213b"
foreground = "#f6e4f3"
dark_foreground = "#c2b0c2"
light_foreground = "#f8e9f5"
bright_foreground = "#faeff8"
red = "#ff929e"
yellow = "#edcf8b"
orange = "#ffb08c"
green = "#85d9ac"
cyan = "#7ddbe4"
blue = "#96baff"
magenta = "#ed98da"
brown = "#cba4a1"
bright_red = "#ffa8b1"
bright_yellow = "#f1d9a2"
bright_green = "#9de1bd"
bright_cyan = "#97e2e9"
bright_blue = "#abc8ff"
bright_magenta = "#f1ade1"
hyprland_active_border = "#ff87d1"
hyprland_inactive_border = "#4e3e56"
